-- JerseyHub: non-destructive product catalog migration
-- Run this file in Supabase SQL Editor.
-- It does not drop tables, delete rows, or recreate the existing schema.

begin;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  club text,
  kit text,
  number integer,
  price integer,
  sale integer,
  color text default '#111111',
  stripe text default '#FFFFFF',
  text_color text,
  image text,
  back_image text,
  available boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.products add column if not exists club text;
alter table public.products add column if not exists kit text;
alter table public.products add column if not exists number integer;
alter table public.products add column if not exists price integer;
alter table public.products add column if not exists sale integer;
alter table public.products add column if not exists color text;
alter table public.products add column if not exists stripe text;
alter table public.products add column if not exists text_color text;
alter table public.products add column if not exists image text;
alter table public.products add column if not exists back_image text;
alter table public.products add column if not exists available boolean;
alter table public.products add column if not exists created_at timestamptz;
alter table public.products add column if not exists updated_at timestamptz;

update public.products
set
  color = coalesce(nullif(trim(color), ''), '#111111'),
  stripe = coalesce(nullif(trim(stripe), ''), '#FFFFFF'),
  available = coalesce(available, true),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, now())
where color is null
   or trim(color) = ''
   or stripe is null
   or trim(stripe) = ''
   or available is null
   or created_at is null
   or updated_at is null;

alter table public.products alter column club set not null;
alter table public.products alter column kit set not null;
alter table public.products alter column price set not null;
alter table public.products alter column color set not null;
alter table public.products alter column stripe set not null;
alter table public.products alter column available set not null;
alter table public.products alter column available set default true;
alter table public.products alter column color set default '#111111';
alter table public.products alter column stripe set default '#FFFFFF';
alter table public.products alter column created_at set default now();
alter table public.products alter column updated_at set default now();

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'products_club_length') then
    alter table public.products add constraint products_club_length
      check (char_length(trim(club)) >= 2);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'products_kit_length') then
    alter table public.products add constraint products_kit_length
      check (char_length(trim(kit)) >= 2);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'products_number_range') then
    alter table public.products add constraint products_number_range
      check (number is null or number between 1 and 99);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'products_price_nonnegative') then
    alter table public.products add constraint products_price_nonnegative
      check (price >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'products_sale_nonnegative') then
    alter table public.products add constraint products_sale_nonnegative
      check (sale is null or sale >= 0);
  end if;
end $$;

create index if not exists products_available_idx
  on public.products (available, id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

alter table public.products enable row level security;

drop policy if exists "Anyone can view available products" on public.products;
create policy "Anyone can view available products"
on public.products for select
using (available = true);

commit;

-- After running this migration, restart the server once.
-- It will seed the existing bundled catalog only when this table is empty.
