-- JerseyHub SL Supabase schema
-- Run this in Supabase Dashboard -> SQL Editor.
-- Passwords and login sessions are managed by Supabase Auth (auth.users).

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null check (char_length(trim(full_name)) >= 2),
  phone text,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  -- Guest/custom checkout orders are allowed to have no authenticated user.
  user_id uuid references auth.users(id) on delete restrict,
  customer_name text not null,
  customer_phone text not null,
  delivery_method text not null check (delivery_method in ('pickup', 'delivery')),
  delivery_address text,
  payment_method text not null check (payment_method in ('monime', 'cash', 'orange_money', 'afrimoney')),
  payment_plan text not null check (payment_plan in ('full', 'deposit', 'pickup')),
  payment_due integer not null check (payment_due >= 0),
  total integer not null check (total >= 0),
  note text,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'fulfilled', 'cancelled')),
  items jsonb not null check (jsonb_typeof(items) = 'array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint delivery_address_required check (
    delivery_method = 'pickup' or char_length(trim(coalesce(delivery_address, ''))) > 0
  )
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  club text not null check (char_length(trim(club)) >= 2),
  kit text not null check (char_length(trim(kit)) >= 2),
  number integer check (number is null or (number between 1 and 99)),
  price integer not null check (price >= 0),
  sale integer check (sale is null or sale >= 0),
  color text not null default '#111111',
  stripe text not null default '#FFFFFF',
  text_color text,
  image text,
  back_image text,
  available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_user_id_created_at_idx
  on public.orders (user_id, created_at desc);

alter table public.orders
  alter column user_id drop not null;

alter table public.orders
  alter column user_id set default auth.uid();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

-- Create a profile automatically after a user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone, role)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), 'JerseyHub customer'),
    nullif(trim(new.raw_user_meta_data ->> 'phone'), ''),
    'customer'
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.products enable row level security;

drop policy if exists "Anyone can view available products" on public.products;
create policy "Anyone can view available products"
on public.products for select
using (available = true);

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
on public.profiles for select
using (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

create or replace function public.prevent_profile_role_change()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if auth.uid() = old.id and new.role is distinct from old.role then
    raise exception 'Users cannot change their profile role';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_prevent_role_change on public.profiles;
create trigger profiles_prevent_role_change
before update of role on public.profiles
for each row execute function public.prevent_profile_role_change();

-- Customers can only see their own orders.
drop policy if exists "Users can view their own orders" on public.orders;
create policy "Users can view their own orders"
on public.orders for select
using (user_id is null or auth.uid() = user_id);

drop policy if exists "Users can create their own orders" on public.orders;
create policy "Users can create their own orders"
on public.orders for insert
with check (user_id is null or auth.uid() = user_id);

-- Admin-only read is enforced by the server-side API and the role column.
create policy "Admins can view all profiles" on public.profiles
for select using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create policy "Admins can view all orders" on public.orders
for select using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

-- Admin access should use a server-side Supabase service-role key.
-- Never expose that key in jersey.html or browser JavaScript.
